/**
 * Fixtures for the printable drill size chart.
 *
 * The chart asserts no new figure — every diameter is generated by
 * `drill-series.ts` and already tested there. What CAN go wrong here is the
 * presentation: a decimal place lost, a unit conversion inverted, or the CSV
 * disagreeing with the printed table. Those are the three things checked.
 *
 * The expected values are exact by definition, not measured, which is why they
 * can be asserted to the last digit:
 *
 *   1 in = 25.4 mm exactly — international yard and pound agreement, 1959,
 *   the basis of ASME B94.11M's fractional inch drill series and of the
 *   metric equivalents printed beside every fractional size in a supplier
 *   catalogue. So 1/4" is 6.350 mm and 1/2" is 12.700 mm with no rounding at
 *   all, and 6.8 mm is 0.267716…" which the chart shows to four places.
 */

import { describe, expect, it } from 'vitest';
import {
  CHART_CSV_HEADER,
  chartCsv,
  chartRows,
  INCH_DECIMALS,
  MM_DECIMALS,
} from '../../src/lib/calc/drill-chart';
import { FRACTIONAL_DRILLS, METRIC_DRILLS } from '../../src/lib/calc/drill-series';

const find = (label: string) => {
  const row = chartRows('both').find((r) => r.label === label);
  if (row === undefined) throw new Error(`no row labelled ${label}`);
  return row;
};

describe('chart rows', () => {
  it('carries every drill in both catalogues and loses none', () => {
    expect(chartRows('metric')).toHaveLength(METRIC_DRILLS.length);
    expect(chartRows('fractional')).toHaveLength(FRACTIONAL_DRILLS.length);
    expect(chartRows('both')).toHaveLength(
      METRIC_DRILLS.length + FRACTIONAL_DRILLS.length,
    );
  });

  it('is ascending by diameter, both catalogues interleaved', () => {
    const diameters = chartRows('both').map((r) => r.nm);
    expect(diameters).toEqual([...diameters].sort((a, b) => a - b));
    // Interleaving is the point of the combined view: 1/64" (0.397 mm) sorts
    // below 0.5 mm, so the first row is fractional even though metric leads
    // the source array.
    expect(
      chartRows('both')
        .slice(0, 2)
        .map((r) => r.label),
    ).toEqual(['1/64"', '0.5 mm']);
  });

  // 1/4" = 6.35 mm exactly (1 in = 25.4 mm, 1959 agreement).
  it('converts a fractional drill to its exact millimetre equivalent', () => {
    expect(find('1/4"').mm).toBe('6.350');
    expect(find('1/4"').inch).toBe('0.2500');
    expect(find('1/2"').mm).toBe('12.700');
  });

  // 6.8 mm / 25.4 = 0.2677165…" — the standard M8 x 1.25 tap drill, the size
  // published charts specify and the one the tap drill calculator returns.
  it('converts a metric drill to its inch equivalent', () => {
    expect(find('6.8 mm').inch).toBe('0.2677');
    expect(find('6.8 mm').mm).toBe('6.800');
  });

  it('prints fixed decimals so a printed column aligns', () => {
    for (const row of chartRows('both')) {
      expect(row.mm.split('.')[1]).toHaveLength(MM_DECIMALS);
      expect(row.inch.split('.')[1]).toHaveLength(INCH_DECIMALS);
    }
  });

  it('renders two rows to the same figure only where the drills truly coincide', () => {
    // 1/2" IS 12.7 mm — exactly, by the 1959 inch. Both marks exist and both
    // rows stay, because a machinist looking for "12.7" and one looking for
    // "1/2" are looking for the same drill and neither should come up empty.
    //
    // Asserting the exact set rather than "no duplicates" keeps the check
    // meaningful: change the decimals and merge two genuinely different sizes,
    // and this fails naming them.
    const byMm = new Map<string, string[]>();
    for (const row of chartRows('both')) {
      byMm.set(row.mm, [...(byMm.get(row.mm) ?? []), row.label]);
    }
    const collisions = [...byMm].filter(([, labels]) => labels.length > 1);
    expect(collisions).toEqual([['12.700', ['12.7 mm', '1/2"']]]);
  });

  it('labels each row with the catalogue it comes from', () => {
    expect(find('6.8 mm').series).toBe('metric');
    expect(find('1/4"').series).toBe('fractional');
  });
});

describe('chart CSV', () => {
  const csv = chartCsv();
  const lines = csv.trimEnd().split('\n');

  it('matches the table row for row', () => {
    expect(lines[0]).toBe(CHART_CSV_HEADER.join(','));
    expect(lines).toHaveLength(chartRows('both').length + 1);
  });

  it('quotes the inch mark rather than emitting a bare double quote', () => {
    // 1/4" unquoted would be `1/4"` — a field a spreadsheet parses wrongly.
    expect(csv).toContain('"1/4""",fractional,6.350,0.2500');
    expect(csv).toContain('6.8 mm,metric,6.800,0.2677');
  });

  it('ends with a newline', () => {
    expect(csv.endsWith('\n')).toBe(true);
  });
});
